[env]
_.file = "~/.config/mise/.env"

[tools]
"cargo:typst-live" = "latest"
bun = "latest"
python = "3.10"
node = "24"
uv = "latest"
luajit = "latest"
clang = "latest"
go = "latest"
dotnet = "latest"
"github:railwayapp/railpack" = "latest"
zig = "latest"
java = "latest"
ollama = "latest"
"cargo:voxquant" = "latest"
"github:zeux/meshoptimizer" = "latest"
"npm:playwright-cli" = "latest"
pkl = "latest"
[settings]
experimental = true
