[symlinks]
"brew/.Brewfile" = "/home/austin/.config/brew/.Brewfile"
"btop/btop.conf" = "/home/austin/.config/btop/btop.conf"
"eza/theme.yaml" = "/home/austin/.config/eza/theme.yaml"
"ghostty/config" = "/home/austin/.config/ghostty/config"
"lazygit/config.yml" = "/home/austin/.config/lazygit/config.yml"
"nvim/.gitignore" = "/home/austin/.config/nvim/.gitignore"
"nvim/.neoconf.json" = "/home/austin/.config/nvim/.neoconf.json"
"nvim/LICENSE" = "/home/austin/.config/nvim/LICENSE"
"nvim/README.md" = "/home/austin/.config/nvim/README.md"
"nvim/init.lua" = "/home/austin/.config/nvim/init.lua"
"nvim/lazyvim.json" = "/home/austin/.config/nvim/lazyvim.json"
"nvim/lua/config/autocmds.lua" = "/home/austin/.config/nvim/lua/config/autocmds.lua"
"nvim/lua/config/keymaps.lua" = "/home/austin/.config/nvim/lua/config/keymaps.lua"
"nvim/lua/config/lazy.lua" = "/home/austin/.config/nvim/lua/config/lazy.lua"
"nvim/lua/config/options.lua" = "/home/austin/.config/nvim/lua/config/options.lua"
"nvim/lua/plugins/colorscheme.lua" = "/home/austin/.config/nvim/lua/plugins/colorscheme.lua"
"nvim/lua/plugins/example.lua" = "/home/austin/.config/nvim/lua/plugins/example.lua"
"nvim/lua/plugins/overseer.lua" = "/home/austin/.config/nvim/lua/plugins/overseer.lua"
"nvim/lua/plugins/tab_complete.lua" = "/home/austin/.config/nvim/lua/plugins/tab_complete.lua"
"nvim/stylua.toml" = "/home/austin/.config/nvim/stylua.toml"
"p10k/config.zsh" = "/home/austin/.config/p10k/config.zsh"
"tmux/tmux.conf" = "/home/austin/.config/tmux/tmux.conf"
"yazi/flavors/monokai-vibrant.yazi/LICENSE" = "/home/austin/.config/yazi/flavors/monokai-vibrant.yazi/LICENSE"
"yazi/flavors/monokai-vibrant.yazi/LICENSE-tmtheme" = "/home/austin/.config/yazi/flavors/monokai-vibrant.yazi/LICENSE-tmtheme"
"yazi/flavors/monokai-vibrant.yazi/README.md" = "/home/austin/.config/yazi/flavors/monokai-vibrant.yazi/README.md"
"yazi/flavors/monokai-vibrant.yazi/flavor.toml" = "/home/austin/.config/yazi/flavors/monokai-vibrant.yazi/flavor.toml"
"yazi/flavors/monokai-vibrant.yazi/preview.png" = "/home/austin/.config/yazi/flavors/monokai-vibrant.yazi/preview.png"
"yazi/flavors/monokai-vibrant.yazi/tmtheme.xml" = "/home/austin/.config/yazi/flavors/monokai-vibrant.yazi/tmtheme.xml"
"yazi/package.toml" = "/home/austin/.config/yazi/package.toml"
"yazi/theme.toml" = "/home/austin/.config/yazi/theme.toml"
"zsh/.zshenv" = "/home/austin/.zshenv"
"zsh/config/.zfunctions/antidote_path" = "/home/austin/.config/zsh/.zfunctions/antidote_path"
"zsh/config/.zfunctions/is_macos" = "/home/austin/.config/zsh/.zfunctions/is_macos"
"zsh/config/.zsh_plugins.txt" = "/home/austin/.config/zsh/.zsh_plugins.txt"
"zsh/config/.zshrc" = "/home/austin/.config/zsh/.zshrc"
"zsh/config/.zshrc.d/aliases.zsh" = "/home/austin/.config/zsh/.zshrc.d/aliases.zsh"
"zsh/config/.zshrc.d/brew.zsh" = "/home/austin/.config/zsh/.zshrc.d/brew.zsh"
"zsh/config/.zshrc.d/history-substring-search.zsh" = "/home/austin/.config/zsh/.zshrc.d/history-substring-search.zsh"
"zsh/config/.zshrc.d/variables.zsh" = "/home/austin/.config/zsh/.zshrc.d/variables.zsh"
"zsh/config/.zshrc.d/zoxide.zsh" = "/home/austin/.config/zsh/.zshrc.d/zoxide.zsh"
"zsh/config/.zstyles" = "/home/austin/.config/zsh/.zstyles"

[templates]
