[helpers]

[default]
depends = []

[default.files]
# vscode = "~/Library/Application Support/Code/User"
nvim = "~/.config/nvim/"
btop = "~/.config/btop/"
eza = "~/.config/eza/"
brew = "~/.config/brew"
lazygit = "~/.config/lazygit/"
yazi = "~/.config/yazi/"
"zsh/config" = "~/.config/zsh"
"zsh/.zshenv" = "~/.zshenv"
"zsh/.hushlogin" = "~/.hushlogin"
p10k = "~/.config/p10k"
tmux = "~/.config/tmux"
ghostty = "~/.config/ghostty"
karabiner = "~/.config/karabiner"
neovide = "~/.config/neovide"
wallpapers = "~/.config/wallpapers"
mise = "~/.config/mise"
gh = "~/.config/gh"
glow = "~/.config/glow"
zed = "~/.config/zed"
serie = "~/.config/serie"
agents = "~/.agents"
agents = "~/.claude"
agents = "~/.codex"
codex = "~/.codex"
bat = "~/.config/bat"
gitlogue = "~/.config/gitlogue"
zen = "/Users/austindelic/Library/Application Support/zen/Profiles/3m7t1b65.Default (release)"
[default.variables]

[settings]
default_target_type = "automatic"
